name: contador
description: "Exemplo de um contador usando o minecore"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  asp: ^1.3.0
  auto_injector: ^2.0.2
  gap: ^3.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
